version: '3'
services:
  selenoid:
    network_mode: host
    image: aerokube/selenoid:latest-release
    volumes:
      - ./configs:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/opt/selenoid/logs
    command: ["-conf", "/etc/selenoid/browsers.json", "-log-output-dir", "/opt/selenoid/logs"]
  maven:
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenoid
